# Generated by Django 3.1.6 on 2021-02-21 06:01

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bjj_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
