# Generated by Django 3.1.6 on 2021-02-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bjj_logs', '0004_entry_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='video',
        ),
    ]
