# Generated by Django 3.1.6 on 2021-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bjj_logs', '0005_remove_entry_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32)),
                ('file_name', models.CharField(max_length=500)),
            ],
        ),
    ]
