# Generated by Django 3.1.6 on 2021-02-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bjj_logs', '0006_videos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
