# Generated by Django 3.1.6 on 2021-02-23 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bjj_logs', '0008_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Youtube',
        ),
    ]
